version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/hfhbd/kobol
    username: hfhbd
    password: ${{secrets.GITHUBPACKAGESPASSWORD }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
